global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: 
        - 'localhost:9090'
  - job_name: network_monitoring
    static_configs:
      - targets: 
        - '10.200.200.102:5000'
