---
spine00:
    nornir_host: 10.200.200.1
    nornir_username: myuser
    nornir_password: mypassword
    nornir_network_api_port: 12443
    nornir_nos: eos

leaf00:
    nornir_host: 10.200.200.1
    nornir_username: myuser
    nornir_password: mypassword
    nornir_network_api_port: 12444
    nornir_nos: eos

leaf01:
    nornir_host: 10.200.200.1
    nornir_username: myuser
    nornir_password: mypassword
    nornir_network_api_port: 12445
    nornir_nos: eos
